const router = require('express').Router()
const account = require('./account')
const admin = require('./admin')
const activityFlower = require('./activityFlower')
const activityVideo = require('./activityVideo')
const activityContest = require('./activityContest')
const activityDinner = require('./activityDinner')
const activityPainting = require('./activityPainting')
const activityWalkRally = require('./activityWalkRally')
const activitySchool = require('./activitySchool')
const controllerVideo = require('./controllerVideo')
const controllerContest = require('./controllerContest')
const controllerInspiration = require('./controllerInspiration')
const controllerAlumni = require('./controllerAlumni')
const setting = require('./setting')
const notification = require('./notification')
const notificationView = require('./notificationView')
const controllerLiveStreaming = require('./controllerLiveStreaming')

const getUser = require ('./userData')
const surway = require('./surway')
const report = require('./report')
const { authenticated, authenticatedAdmin } = require('../configs/security')

// หน้า login
router.use('/account', account)
router.use('/admin', admin)
// Activity
router.use('/activityFlower', activityFlower)
router.use('/activityDinner', authenticated, activityDinner)
router.use('/activityPainting', authenticated, activityPainting)
router.use('/activityWalkRally', authenticated, activityWalkRally)
router.use('/activityContest', activityContest)
router.use('/activityVideo', authenticated, activityVideo)
router.use('/activitySchool', authenticated, activitySchool)
// Controller
router.use('/controllerVideo', controllerVideo)
router.use('/controllerContest', controllerContest)
router.use('/controllerAlumni', controllerAlumni)
router.use('/controllerInspiration', controllerInspiration)
router.use('/controllerLiveStreaming', controllerLiveStreaming)
router.use('/setting', setting)
router.use('/notification', notification)
router.use('/notificationView', notificationView)

// Surway
router.use('/surway', surway)
router.use('/report', report)
router.use('/getuser', getUser)
module.exports = router;
